const lyricsDatabase = {
    "timmcgraw": "He said the way my blue eyes shined\nPut those Georgia stars to shame that night\nI said, \"That's a lie\"\nJust a boy in a Chevy truck\nThat had a tendency of gettin' stuck\nOn backroads at night\nAnd I was right there beside him all summer long\nAnd then the time we woke up to find that summer gone\n\nBut when you think Tim McGraw\nI hope you think my favorite song\nThe one we danced to all night long\nThe moon like a spotlight on the lake\nWhen you think happiness\nI hope you think that little black dress\nI hope you think of my head on your chest\nAnd my old faded blue jeans\nWhen you think Tim McGraw\nI hope you think of me\n\nSeptember saw a month of tears\nAnd lookin' back on all those years\nI can't believe I'm wishin' you were here\nOur distant memory with structural grace\nAnd you're back here in this place\n\nBut when you think Tim McGraw\nI hope you think my favorite song\nThe one we danced to all night long\nThe moon like a spotlight on the lake\nWhen you think happiness\nI hope you think that little black dress\nI hope you think of my head on your chest\nAnd my old faded blue jeans\nWhen you think Tim McGraw\nI hope you think of me\n\nI'm back for the first time since then\nI'm standin' on your street\nAnd there's a letter on your doorstep\nAnd the first thing that you'll read is:\n\nWhen you think Tim McGraw\nI hope you think my favorite song\nSomeday you'll turn your radio on\nI hope it takes you back to that place\nWhen you think happiness\nI hope you think that little black dress\nI hope you think of my head on your chest\nAnd my old faded blue jeans\nWhen you think Tim McGraw\nI hope you think of me\nOh, think of me\nMmm",

    "theoutside": "I didn't know what I would find\nWhen I went looking for a reason, I know I didn't read between the lines\nAnd I've tried to take the road less traveled by\nBut empty rooms inside my mind can make me feel so low at times\n\nHow can I ever try to be fine\nWhen the pieces of my heart are left on the outside?\nYeah, you leave me standing on the outside\n\nYou saw me standing by the door\nBut you didn't see the tears or how I fell onto the floor\nAnd you think that I don't care at all\nBut I'm just building up a wall so high that I won't ever fall\n\nHow can I ever try to be fine\nWhen the pieces of my heart are left on the outside?\nYeah, you leave me standing on the outside\n\nI tried to look back on the good times\nBut they're fading into grey and everything's a shadow now\nAnd I'm just trying to make it through the day\n\nHow can I ever try to be fine\nWhen the pieces of my heart are left on the outside?\nYeah, you leave me standing on the outside\nYeah, on the outside\nOh, on the outside",

    "oursong": "I was ridin' shotgun with my hair undone\nIn the front seat of his car\nHe's got a one-hand feel on the steering wheel\nThe other on my heart\nI look around, turn the radio down\nHe says, \"Baby, is something wrong?\"\nI say, \"Nothing, I was just thinkin' how we don't have a song\"\nAnd he says\n\nOur song is the slamming screen door\nSneakin' out late, tapping on his window\nWhen we're on the phone and he talks real slow\n'Cause it's late and his mama don't know\nOur song is the way he laughs\nThe first date \"Man, I didn't kiss her, and I should have\"\nAnd when I got home, 'fore I said my prayers\nI poured my heart out into a cup\nAnd I played it again\n\nI was walking up the front steps after everything that day\nHad gone all wrong and been tripped up\nAnd inside the house, I could hear his voice\nSaying it's all gonna be okay\n\nOur song is the slamming screen door\nSneakin' out late, tapping on his window\nWhen we're on the phone and he talks real slow\n'Cause it's late and his mama don't know\nOur song is the way he laughs\nThe first date \"Man, I didn't kiss her, and I should have\"\nAnd when I got home, 'fore I said my prayers\nI poured my heart out into a cup\nAnd I played it again\n\nI've heard every album, listened to the radio\nWaiting for something to come along and match the feeling\nBut nothing ever does\n\nOur song is the slamming screen door\nSneakin' out late, tapping on his window\nWhen we're on the phone and he talks real slow\n'Cause it's late and his mama don't know\nOur song is the way he laughs\nThe first date \"Man, I didn't kiss her, and I should have\"\nAnd when I got home, 'fore I said my prayers\nI poured my heart out into a cup\nAnd I played it again\n\nOh, yeah\nI played it again\nI was ridin' shotgun with my hair undone\nIn the front seat of his car\nYeah, we're playin' our song",

    "picturetoburn": "State the obvious, I didn't get my perfect fantasy\nI realize you love yourself more than you could ever love me\nSo go and tell your friends that I'm obsessive and crazy\nThat's fine, I'll tell mine that you're gay\nAnd by the way\n\nI hate that stupid old pickup truck you never let me drive\nYou're a redneck heartbreak who's really bad at lying\nSo watch me strike a match on all my wasted time\nAs far as I'm concerned, you're just another picture to burn\n\nThere's no time for tears\nI'm just sitting here planning my revenge\nThere's nothing stopping me\nFrom going out with all of your best friends\nAnd if you come around saying sorry to me\nMy mama's gonna show you how sorry you'll be\n\n'Cause I hate that stupid old pickup truck you never let me drive\nYou're a redneck heartbreak who's really bad at lying\nSo watch me strike a match on all my wasted time\nAs far as I'm concerned, you're just another picture to burn\n\nIf you're missing me, you'd better keep it to yourself\n'Cause I'm coming clean, and I'm burning your pictures now\n\nI hate that stupid old pickup truck you never let me drive\nYou're a redneck heartbreak who's really bad at lying\nSo watch me strike a match on all my wasted time\nAs far as I'm concerned, you're just another picture to burn\n\nBurn, burn, burn, baby, burn\nJust another picture to burn\nBaby, burn",

    "tiedtogetherwithasmile": "Seems the only one who doesn't see your beauty\nIs the face in the mirror looking back at you\nYou walk around here thinkin' you're not pretty\nBut that's not true, 'cause I know you\n\nAnd you tie your hair up with a ribbon\nAnd you walk out into the world\nAnd you're tied together with a smile\nBut you're coming undone, oh, you're coming undone\n\nGoodbye to all the inner demons\nGoodbye to all the visual threats\nI see you running through the dark lines\nTrying to make it look like you're okay\nBut you don't have to hide from me\n\nAnd you tie your hair up with a ribbon\nAnd you walk out into the world\nAnd you're tied together with a smile\nBut you're coming undone, oh, you're coming undone\n\nI guess it's true that you're a beauty\nBut you don't even know it yet\nAnd it's a shame that you're so empty\nInside your head, inside your head\n\nAnd you tie your hair up with a ribbon\nAnd you walk out into the world\nAnd you're tied together with a smile\nBut you're coming undone, oh, you're coming undone",

    "imonlymewhenimwithyou": "Just a small-town girl and a small-town boy\nLiving in a world that can be so cold\nBut we got something that can never be destroyed\nNo matter what they say, we hold the gold\n\nAnd I'm only me when I'm with you\nYeah, I'm only me when I'm with you\nEverything I do is better when you're there\n\nYou know everything about my dark secrets\nAnd you still choose to stay right by my side\nYou're the only one who truly gets it\nWe don't ever have to hide\n\nAnd I'm only me when I'm with you\nYeah, I'm only me when I'm with you\nEverything I do is better when you're there\n\nWhen I'm with you, the world just fades away\nAnd everything is perfectly okay\n\nAnd I'm only me when I'm with you\nYeah, I'm only me when I'm with you\nEverything I do is better when you're there\nYeah, with you",

    "teardropsonmyguitar": "Drew looks at me, I fake a smile so he won't see\nThat I want and I'm needing everything that we should be\nI'll bet she's beautiful, that girl he talks about\nAnd she's got everything that I have to live without\n\nDrew talks to me, I laugh 'cause it's so damn funny\nBut I can't even see anyone else when he's around\nHe says he's so in love, he's finally got it right\nI wonder if he knows he's all I think about at night\n\nHe's the reason for the teardrops on my guitar\nThe only thing that keeps me wishing on a wishing star\nHe's the song in the car I keep singing, don't know why I do\n\nHe walks by me, can't look straight into his eyes\n'Cause if I do, I might just break down and cry\nSo I'll just sit here and pretend that everything is fine\nEven though I know he'll never be mine\n\nHe's the reason for the teardrops on my guitar\nThe only thing that keeps me wishing on a wishing star\nHe's the song in the car I keep singing, don't know why I do\n\nSo I'll just drive home alone in the dark\nWith his name written all over my heart\n\nHe's the reason for the teardrops on my guitar\nThe only thing that keeps me wishing on a wishing star\nHe's the song in the car I keep singing, don't know why I do\nYeah, Drew",

    "staybeautiful": "Cory's eyes are like a jungle, he smiles, it's like the radio\nHe whispers songs into my ear that I don't even know\nHe's got a way of making me feel like I'm the only girl\nIn the entire wide world\n\nAnd I hope you stay beautiful, Cory, I do\nI hope you find everything you're looking for out there\nAnd if you ever change your mind, you know where I'll be\nRight here, wishing you the best\n\nYou look so cool when you're walking down the street\nWith your hands in your pockets and your headphones on\nI can't help but wonder if you're thinking of me\nOr if I'm already gone\n\nAnd I hope you stay beautiful, Cory, I do\nI hope you find everything you're looking for out there\nAnd if you ever change your mind, you know where I'll be\nRight here, wishing you the best\n\nCory, you're the one I want to see standing across from me\n\nAnd I hope you stay beautiful, Cory, I do\nI hope you find everything you're looking for out there\nAnd if you ever change your mind, you know where I'll be\nRight here, wishing you the best\nYeah, Cory",

    "invisible": "She can't see the way I look at her when she walks by\nShe don't know how much I want to hold her tight\nTo her, I'm just a shadow in the background light\nPerfectly invisible\n\nAnd you don't even know that I'm alive\nYeah, you leave me standing on the outside lines\nI'm invisible to you, and it cuts like a knife\n\nI see you laughing with your friends over there\nAnd I pretend that I don't even care at all\nBut inside, I'm breaking down and ready to fall\nStraight into your arms\n\nAnd you don't even know that I'm alive\nYeah, you leave me standing on the outside lines\nI'm invisible to you, and it cuts like a knife\n\nMaybe someday you'll turn around and see\nThat the one you've been searching for is me\n\nAnd you don't even know that I'm alive\nYeah, you leave me standing on the outside lines\nI'm invisible to you, and it cuts like a knife\nYeah, invisible",

    "aplaceinthisworld": "I don't know what I'm supposed to do with myself tonight\nEverything feels so heavy and nothing feels right\nI'm just a girl trying to find her way in the dark\nLooking for a spark\n\nAnd I'm alone, on my own, and that's all right\nI'm just trying to find a place in this world tonight\nYeah, a place in this world\n\nTomorrow is another day to start all over again\nMaybe I'll find a way to make a brand new friend\nWho understands exactly what I'm going through\nAnd knows what to do\n\nAnd I'm alone, on my own, and that's all right\nI'm just trying to find a place in this world tonight\nYeah, a place in this world\n\nI'm spinning around in this big old town\nTrying to keep my feet on the ground\n\nAnd I'm alone, on my own, and that's all right\nI'm just trying to find a place in this world tonight\nYeah, a place in this world\nOh, a place in this world",

    "shouldhavesaidno": "It's strange to think the songs we used to sing together\nAre now just echoes of a past that's gone forever\nYou should have thought about the consequences of your actions\nBefore you made your moves\n\nAnd you should have said no, you should have gone home\nYou should have thought twice 'fore you let it all go\nYou should have known better than to cheat on me\nYeah, you should have said no\n\nI see the look in your eyes and I know you're lying\nYou can't even look straight at me without crying\nYou say you're sorry and you want a second chance\nBut therein lies the problem\n\nAnd you should have said no, you should have gone home\nYou should have thought twice 'fore you let it all go\nYou should have known better than to cheat on me\nYeah, you should have said no\n\nI gave you everything I had to give\nAnd this is how you repay me for the way we lived?\n\nAnd you should have said no, you should have gone home\nYou should have thought twice 'fore you let it all go\nYou should have known better than to cheat on me\nYeah, you should have said no\nOh, you should have said no",

    "aperfectlygoodsong": "Why would you want to break a perfectly good heart?\nWhy would you want to take our love and tear it apart?\nI thought we had something that could never be broken\nBut now I'm left with words unspoken\n\nAnd you left me standing in the pouring rain\nWith nothing but my heart and all this pain\nWhy would you do that to me, baby?\n\nI look at your pictures and I can't help but wonder\nHow we let everything slip out and go under\nYou were the one I trusted with my soul\nAnd now I'm losing all control\n\nAnd you left me standing in the pouring rain\nWith nothing but my heart and all this pain\nWhy would you do that to me, baby?\n\nWhy would you break a perfectly good song?\n\nAnd you left me standing in the pouring rain\nWith nothing but my heart and all this pain\nWhy would you do that to me, baby?\nYeah, a perfectly good song",

    "coldasyou": "You have a way of coming easily to me\nAnd then you leave me standing here in the cold, freeze\nI never knew someone could be so beautiful and harsh\nLeaving your marks all over my heart\n\nAnd I'm as cold as you, yeah, I'm as cold as you\nYou left me waiting in the dark lines, out of view\n\nI tried to be everything you wanted me to be\nBut it was never enough for you to see me\nYou took my love and you threw it all away\nAnd now I have nothing left to say to you\n\nAnd I'm as cold as you, yeah, I'm as cold as you\nYou left me waiting in the dark lines, out of view\n\nNow I'm moving on and I'm finding my own way\nWithout you blocking up my everyday\n\nAnd I'm as cold as you, yeah, I'm as cold as you\nYou left me waiting in the dark lines, out of view\nYeah, as cold as you",

    "maryssong": "She said I was seven and you were nine\nLookin' at each other through the backyard clothesline\nOur mamas were best friends and we were inseparable\nEverything was beautiful and simple\n\nAnd you said, \"Marry me, Mary, I'll be your king\nAnd you'll be my queen over everything\"\nWe were just kids back then, didn't know a thing\n\nThen we grew up and things began to change around\nWe fell in love in this small country town\nAnd you held my hand as the sun went down behind the trees\nAnd you got down on your knees\n\nAnd you said, \"Marry me, Mary, I'll be your king\nAnd you'll be my queen over everything\"\nAnd now we're old and grey, but we still sing\n\nOur love story is the one they'll tell for years\nThrough all the laughter and all the tears\n\nAnd you said, \"Marry me, Mary, I'll be your king\nAnd you'll be my queen over everything\"\nAnd now we're old and grey, but we still sing\nYeah, we still sing\nI was seven and you were nine"
};

document.addEventListener("DOMContentLoaded", () => {
    const songs = document.querySelectorAll(".song");
    const display = document.getElementById("lyrics-content");

    songs.forEach(song => {
        song.addEventListener("click", () => {
            songs.forEach(s => s.classList.remove("active"));
            song.classList.add("active");

            const songId = song.getAttribute("data-song");
            display.innerText = lyricsDatabase[songId] || "Lyrics not found.";
            
            // Auto resets layout view container smoothly back to top
            document.querySelector(".lyrics-screen").scrollTop = 0;
        });
    });
});