const lyricsDatabase = {
    "readyforit": "Knew he was a killer first time that I saw him\nWondered how many girls he had loved and left haunted\nBut if he's a ghost, then I can be a fantasy\nAnd he can be my jailer, Burton to this Taylor\nEvery lover known in comparison is a failure\nI forget their names now, I'm so changed now\n\nIn the middle of the night, in my dreams\nYou should see the things we do, baby\nIn the middle of the night, in my dreams\nI know I'm gonna be with you\nSo I take my time\nAre you ready for it?\n\nKnew I was a robber first time that he saw me\nStealing hearts and running off and never saying sorry\nBut if I'm a thief, then he can join the heist\nAnd we'll move to an island, and he can be my jailer\nBurton to this Taylor\nEvery lover known in comparison is a failure\nI forget their names now, I'm so changed now\n\nIn the middle of the night, in my dreams\nYou should see the things we do, baby\nIn the middle of the night, in my dreams\nI know I'm gonna be with you\nSo I take my time\nAre you ready for it?\n\nBaby, let the games begin\nLet the games begin\nLet the games begin\nBaby, let the games begin\nLet the games begin\nLet the games begin\n\nI see nothing better, I keep him forever\nLike a vendetta-ta\nI see nothing better, I keep him forever\nLike a vendetta-ta\n\nIn the middle of the night, in my dreams\nYou should see the things we do, baby\nIn the middle of the night, in my dreams\nI know I'm gonna be with you\nSo I take my time\nIn the middle of the night, in my dreams\nYou should see the things we do, baby\nIn the middle of the night, in my dreams\nI know I'm gonna be with you\nSo I take my time\nAre you ready for it?\n\nBaby, let the games begin\nLet the games begin\nLet the games begin\nAre you ready for it?\nBaby, let the games begin\nLet the games begin\nLet the games begin",

    "endgame": "I wanna be your endgame\nI wanna be your first string\nI wanna be your A-Team\nI wanna be your endgame, endgame\n\nBig reputation, big reputation\nOoh, you and me we got big reputations\nAh, and you heard about me\nOh, I got some big enemies\nBig reputation, big reputation\nOoh, you and me would be a big conversation\nAh, and I heard about you\nOoh, I got some big enemies\n\nI got some big reputation, ah\nI wanna be your endgame\nI wanna be your first string\nI wanna be your A-Team\nI wanna be your endgame, endgame\n\nKnew bad guys and bad habits\nFirst stage was crazy, the second stage was a classic\nThird stage was packing up backwards, up in the castle\nChanging your code, trying to glitch your system\nI got hit with a vision, matching outfits and dynamic duos\nAnd making a killing, holding hands in the front row\nAnd making history, so let's write a story\nWhere we end up together, and we are the end game\n\nI wanna be your endgame\nI wanna be your first string\nI wanna be your A-Team\nI wanna be your endgame, endgame\n\nI hit the court and I'm hitting a home run\nI hit the switch and I'm letting the world run\nDrinking your rum, playing your game, under your thumb\nYour love is a drug, I am your plug\nAnd you know that we got it, don't want no static\nI got a big reputation, you love the magic\nI wanna be your first string, I wanna be your A-Team\nI wanna be your endgame\n\nI wanna be your endgame\nI wanna be your first string\nI wanna be your A-Team\nI wanna be your endgame, endgame\n\nAnd I can't let you go, your hand print's on my soul\nIt's like your eyes are liquor, it's like your body's gold\nYou've been calling my bluff on all my usual tricks\nSo here's the truth from my lips\nI wanna be your endgame\nI wanna be your first string\nI wanna be your A-Team\nI wanna be your endgame, endgame",

    "ididsomethingbad": "I never trust a narcissist, but they love me\nSo I play 'em like a violin\nAnd I make it look so easy\n'Cause for every lie I tell, they tell me three\nThis is how the world works\nNow all he thinks about is me\n\nI did something bad, then why's it feel so good?\nMost fun I ever had\nAnd I'd do it over and over and over again if I could\nIt feels so good, good\n\nI never trust a playboy, but they love me\nSo I fly 'em all around the world\nAnd I let them think they saved me\nThey never see it coming, what I do next\nThis is how the world works\nYou gotta leave before you get left\n\nI did something bad, then why's it feel so good?\nMost fun I ever had\nAnd I'd do it over and over and over again if I could\nIt feels so good, good\n\nThey're burning all the witches, even if you aren't one\nThey got their pitchforks and proof\nTheir receipts and reasons\nThey're burning all the witches, even if you aren't one\nSo light me up, light me up, light me up\nGo ahead and light me up\n\nThey say I did something bad, then why's it feel so good?\nMost fun I ever had\nAnd I'd do it over and over and over again if I could\nIt feels so good, good\n\nOh, you gotta leave before you get left\nSo light me up, light me up, light me up\nGo ahead and light me up",

    "dontblameme": "Don't blame me, love made me crazy\nIf it doesn't, you ain't doin' it right\nLord, save me, my drug is my baby\nI'll be usin' for the rest of my life\n\nI've been breakin' hearts a long time, and\nToyin' with them older guys\nJust playin' request tests\nI Knew I was a robber first time that he saw me\nStealing hearts and running off and never saying sorry\nBut something altered when I saw your face\n\nDon't blame me, love made me crazy\nIf it doesn't, you ain't doin' it right\nLord, save me, my drug is my baby\nI'll be usin' for the rest of my life\n\nMy name is whatever you decide\nAnd I'm just gonna call you mine\nI'm insane, but I'm your star\nEchoes of your name inside my mind\nHalo hiding my dark side\nSomething altered when I saw your face\n\nDon't blame me, love made me crazy\nIf it doesn't, you ain't doin' it right\nLord, save me, my drug is my baby\nI'll be usin' for the rest of my life\n\nI get so high every time you're, you're lovin' me\nYou're lovin' me\nTrip of my life every time you're, you're lovin' me\n\nEvery time you're lovin' me\nOh, Lord, save me, my drug is my baby\nI'll be usin' for the rest of my life\n\nDon't blame me, love made me crazy\nIf it doesn't, you ain't doin' it right\nLord, save me, my drug is my baby\nI'll be usin' for the rest of my life",

    "delicate": "Dive bar on the East Side, where you at?\nPhone lights up my nightstand in the black\nCome here, you can meet me in the back\nDark jeans and your Nikes, look at you\nOh damn, never seen that color blue\nJust think of the fun things we could do\n\n'Cause I know that it's delicate\nIsn't it? Isn't it? Isn't it?\nIsn't it? Isn't it? Isn't it?\nIsn't it?\nIs it cool that I said all that?\nIs it too soon to do this yet?\n'Cause I know that it's delicate\nIsn't it? Isn't it? Isn't it?\nIsn't it delicate?\n\nThird floor on the West Side, me and you\nHands drop to our sides, what to do?\nLong night with your hands up in my hair\nEchoes of your footsteps on the stairs\nStay here, honey, I don't wanna share\n'Cause I know that it's delicate\n\nIsn't it? Isn't it? Isn't it?\nIsn't it? Isn't it? Isn't it?\nIsn't it?\nIs it cool that I said all that?\nIs it too soon to do this yet?\n'Cause I know that it's delicate\nIsn't it? Isn't it? Isn't it?\nIsn't it delicate?\n\nSometimes I wonder when you sleep\nAre you dreaming of me?\nSometimes I'm running through your mind\nAnd it's all right, it's safe here\n\nDive bar on the East Side, where you at?\nPhone lights up my nightstand in the black\nCome here, you can meet me in the back\n\nIs it cool that I said all that?\nIs it too soon to do this yet?\n'Cause I know that it's delicate\nIsn't it? Isn't it? Isn't it?\nIs it cool that I said all that?\nIs it too soon to do this yet?\n'Cause I know that it's delicate\nIsn't it? Isn't it? Isn't it?\nIsn't it delicate?",

    "lwymmd": "I don't like your little games\nDon't like your tilted stage\nThe role you made me play\nOf the fool, no, I don't like you\nI don't like your perfect crime\nHow you laugh when you lie\nYou said the gun was mine\nIsn't cool, no, I don't like you\n\nBut I got smarter, I got harder in the nick of time\nHoney, I rose up from the dead, I do it all the time\nI got a list of names, and yours is in red, underlined\nI check it once, then I check it twice, oh\n\nOoh, look what you made me do\nLook what you made me do\nLook what you just made me do\nLook what you just made me do\n\nI don't like your kingdom keys\nThey once belonged to me\nYou asked me for a place to sleep\nLocked me out and threw a feast\n\nBut I got smarter, I got harder in the nick of time\nHoney, I rose up from the dead, I do it all the time\nI got a list of names, and yours is in red, underlined\nI check it once, then I check it twice, oh\n\nOoh, look what you made me do\nLook what you made me do\nLook what you just made me do\nLook what you just made me do\n\nI don't trust nobody and nobody trusts me\nI'll be the actress starring in your bad dreams\nI don't trust nobody and nobody trusts me\nI'll be the actress starring in your bad dreams\n\n\"I'm sorry, the old Taylor can't come to the phone right now.\"\n\"Why? Oh, 'cause she's dead!\"\n\nOoh, look what you made me do\nLook what you made me do\nLook what you just made me do\nLook what you just made me do",

    "soitgoes": "See you in the dark\nAll eyes on us\nYou make me laugh but it's not funny\n'Cause so it goes\nI'm yours to keep\nAnd I'm yours to lose\nYou know I'm not a bad girl, but I\nDo bad things with you\n\nSo it goes, so it goes\nSo it goes\n1, 2, 3, caught up in you\nSo it goes, so it goes\nSo it goes\n\nMet you in a bar\nAll text no calls\nNow you're pulling up beside my window\nAnd so it goes\nI'm yours to keep\nAnd I'm yours to lose\nYou know I'm not a bad girl, but I\nDo bad things with you\n\nSo it goes, so it goes\nSo it goes\n1, 2, 3, caught up in you\nSo it goes, so it goes\nSo it goes\n\nAnd our pieces fall\nRight into place\nGet you up against the wall with my teeth\nIn your face\nAnd our pieces fall\nRight into place\nYou make me scratch your back, look at us\nScratches on your face\n\nSee you in the dark\nAll eyes on us\nYou make me laugh but it's not funny\n'Cause so it goes\nI'm yours to keep\nAnd I'm yours to lose\nYou know I'm not a bad girl, but I\nDo bad things with you\n\nSo it goes, so it goes\nSo it goes\n1, 2, 3, caught up in you\nSo it goes, so it goes\nSo it goes",

    "gorgeous": "You're so gorgeous\nI can't say anything to your face\n'Cause look at your face\nAnd I'm so furious\nAt you for making me feel this way\nBut what can I say?\nYou're gorgeous\n\nYou should take it as a compliment\nThat I'm talking to everyone here but you\nAnd you should think about the consequence\nOf your magnetic field being a little too strong\nAnd I got a boyfriend, he's older than us\nHe's in the club doing I don't know what\nYou're so cool, it makes me hate you so much\n\nwhiskey on ice, Sunset and Vine\nYou've ruined my life by not being mine\n\nYou're so gorgeous\nI can't say anything to your face\n'Cause look at your face\nAnd I'm so furious\nAt you for making me feel this way\nBut what can I say?\nYou're gorgeous\n\nThere's nothing I hate more than jealousy\nBut I guess I'm jealous of your cool friends\nAnd I'm so glad that you're making fun of me\nBecause I can't look straight into those ocean eyes\nAnd I'm so furious at you for making me feel this way\n\nYou're so gorgeous\nI can't say anything to your face\n'Cause look at your face\nAnd I'm so furious\nAt you for making me feel this way\nBut what can I say?\nYou're gorgeous\n\nYou make me so happy, it turns to blue\nThere's nothing I hate more than losing you\nYou're so gorgeous\nI can't say anything to your face\n'Cause look at your face\nAnd I'm so furious\nAt you for making me feel this way\nBut what can I say?\nYou're gorgeous",

    "getawaycar": "It was the best of times, the worst of crimes\nI struck a match and blew your mind\nBut I didn't mean it, and you didn't see it\nThe ties were black, the lies were white\nIn shades of gray in candle light\nI wanted to leave him, I needed a reason\n\nNo, nothing good starts in a getaway car\nNo, nothing good starts in a getaway car\nIt was the crime of the century\nOh, look at us making our final plea\nAnd I knew it from the first Old Fashioned we were cursed\nWe never had a shotgun shotgun shot at it\n\nThere we were flying, but we'd never survive\nDon't pretend it's such a mystery\nThink about the place where you first met me\nWe were driving in a getaway car\nWe were flying, but we'd never survive\n\nNo, nothing good starts in a getaway car\nNo, nothing good starts in a getaway car\nIt was the crime of the century\nOh, look at us making our final plea\nAnd I knew it from the first Old Fashioned we were cursed\nWe never had a shotgun shot at it\n\nI switched to the other side\nAnd I knew it from the first moment I look in your eyes\nThat you were going down, down, down\nAnd I was moving on, on, on\n\nNo, nothing good starts in a getaway car\nNo, nothing good starts in a getaway car\nIt was the crime of the century\nOh, look at us making our final plea\nAnd I knew it from the first Old Fashioned we were cursed\nWe never had a shotgun shot at it\n\nWe were driving in a getaway car\nWe were flying, but we'd never survive\nNo, nothing good starts in a getaway car",

    "kingofmyheart": "I'm perfectly fine, I live on my own\nTo my broken bones\nMy salute to our separate paths\nI'm perfectly fine, I'm okay with being alone\nUntil you came along\n\nAnd all at once you are the one I have been waiting for\nKing of my heart, body and soul, ooh-whoa\nAnd all at once you're all I want, I'll never let you go\nKing of my heart, body and soul, ooh-whoa\nAnd all at once\n\nLate night, your car, your touch in the dark\nWe rule the kingdom inside our room\nYour love is a secret I'm choosing to keep\nAnd all at once you are the one I have been waiting for\n\nAnd all at once you are the one I have been waiting for\nKing of my heart, body and soul, ooh-whoa\nAnd all at once you're all I want, I'll never let you go\nKing of my heart, body and soul, ooh-whoa\n\nIs it true that you love me, or am I just dreaming?\nIs it true that you love me, or am I just dreaming?\nYour love is a secret I'm choosing to keep\n\nAnd all at once you are the one I have been waiting for\nKing of my heart, body and soul, ooh-whoa\nAnd all at once you're all I want, I'll never let you go\nKing of my heart, body and soul, ooh-whoa\nAnd all at once\nKing of my heart, body and soul, ooh-whoa\nKing of my heart, body and soul, ooh-whoa",

    "dwhnt": "Oh, 2 AM, in your car\nWindows down, a love shot in the dark\nAnd you're dancing with our hands tied\nInside the room as it's burning down\nBaby, it's a cold world out there, but you're warm with me\nAnd you're dancing with our hands tied\n\nI, I loved you in secret\nFirst sight, yeah, we love without reason\nOh, twenty-five years too late\nI, I loved you in spite of\nDeep fears that the world would divide us\nSo baby, let's make our escape\n\nYeah, we're dancing with our hands tied\nDancing with our hands tied\nInside the room as it's burning down\nBaby, it's a cold world out there, but you're warm with me\nAnd you're dancing with our hands tied\n\nI, I loved you in secret\nFirst sight, yeah, we love without reason\nOh, twenty-five years too late\nI, I loved you in spite of\nDeep fears that the world would divide us\nSo baby, let's make our escape\n\nYeah, we're dancing with our hands tied\nDancing with our hands tied\nInside the room as it's burning down\nBaby, it's a cold world out there, but you're warm with me\nAnd you're dancing with our hands tied\n\nAnd I'd hold you as the water rushes in\nIf I could dance with you again\nYeah, we're dancing with our hands tied\nDancing with our hands tied\nInside the room as it's burning down\nBaby, it's a cold world out there, but you're warm with me\nAnd you're dancing with our hands tied",

    "dress": "Our secret moments in a crowded room\nThey got no idea about me and you\nThere is an indentation in the shape of you\nMade your mark on me, a golden tattoo\n\nSay my name and everything just stops\nI don't want you like a best friend\nOnly bought this dress so you could take it off\nTake it off\nCarve your name into my bedpost\n'Cause I don't want you like a best friend\nOnly bought this dress so you could take it off\nTake it off\n\nFlashback when you met me\nYour buzzcut and my hair bleached\nEven in my worst times, you saw the best of me\nFlashback to my mistakes\nMy rebounds, my earthquakes\nEven in my worst light, you saw the truth in me\n\nSay my name and everything just stops\nI don't want you like a best friend\nOnly bought this dress so you could take it off\nTake it off\nCarve your name into my bedpost\n'Cause I don't want you like a best friend\nOnly bought this dress so you could take it off\nTake it off\n\nThere is an indentation in the shape of you\nMade your mark on me, a golden tattoo\nSay my name and everything just stops\nI don't want you like a best friend\nOnly bought this dress so you could take it off\nTake it off\nCarve your name into my bedpost\n'Cause I don't want you like a best friend\nOnly bought this dress so you could take it off\nTake it off",

    "tiwwchnt": "This is why we can't have nice things, darling\nBecause you break them, I had to take them away\nThis is why we can't have nice things, honey\nDid you think I wouldn't hear all the things you said about me?\nThis is why we can't have nice things\n\nIt was so nice being friends again\nThere I was giving you a second chance\nBut you stabbed me in the back while you were shaking my hand\nAnd therein lies the issue\nFriends don't try to trick you\nGet you on the phone and mind-twist you\nAnd so I took your name off my list\n\nThis is why we can't have nice things, darling\nBecause you break them, I had to take them away\nThis is why we can't have nice things, honey\nDid you think I wouldn't hear all the things you said about me?\nThis is why we can't have nice things\n\nHere's a toast to my real friends\nThey don't care about the he-said-she-said\nAnd here's to my baby\nHe ain't reading what they call me lately\nAnd here's to my mama\nHad to listen to all this drama\nAnd here's to you\n'Cause forgiveness is a nice thing to do\nHaha, I can't even say it with a straight face\n\nThis is why we can't have nice things, darling\nBecause you break them, I had to take them away\nThis is why we can't have nice things, honey\nDid you think I wouldn't hear all the things you said about me?\nThis is why we can't have nice things",

    "ciwyw": "My castle crumbled overnight\nI brought a knife to a gunfight\nThey took the crown, but it's alright\nAll the liars are calling me one\nNobody's heard from me for months\nI'm doing better than I ever was\n\n'Cause my baby's fit like a daydream\nWalking with his head down, I'm the one he's walking to\nCall it what you want, yeah, call it what you want to\nMy baby's fly like a jet stream\nHigh above the whole scene, loves me like I'm brand new\nCall it what you want, yeah, call it what you want to\n\nAll my flowers grew back as thorns\nWindows boarded up after the storm\nHe built a fire just to keep me warm\nAll the drama queens taking swings\nAll the jokers dressing up as kings\nThey fade to nothing when I look at him\n\nI know I make the same mistakes time and time again\nBut up there on his tower, he loves me without conditions\n\n'Cause my baby's fit like a daydream\nWalking with his head down, I'm the one he's walking to\nCall it what you want, yeah, call it what you want to\nMy baby's fly like a jet stream\nHigh above the whole scene, loves me like I'm brand new\nCall it what you want, yeah, call it what you want to\n\nCall it what you want, yeah, call it what you want to\nCall it what you want, yeah, call it what you want to\nCall it what you want, yeah, call it what you want to\nCall it what you want, yeah, call it what you want to",

    "newyearsday": "There's glitter on the floor after the party\nGirls carrying their shoes down the lobby\nCandle wax and Polaroids on the hardwood floor\nYou squeeze my hand as three o'clock cuts through the night\n\nDon't read the last page\nI want your midnights\nBut I'll be cleaning up bottles with you on New Year's Day\n\nYou skip the conversation when you know it's heavy\nYou squeeze my hand and tell me everything is ready\nI stay up with you when you're running out of steam\nYou're the one I want to see standing across from me\n\nDon't read the last page\nI want your midnights\nBut I'll be cleaning up bottles with you on New Year's Day\n\nPlease don't ever become a stranger\nWhose laugh I could recognize anywhere\nPlease don't ever become a stranger\nWhose laugh I could recognize anywhere\n\nThere's glitter on the floor after the party\nGirls carrying their shoes down the lobby\nCandle wax and Polaroids on the hardwood floor\nYou squeeze my hand as three o'clock cuts through the night\n\nDon't read the last page\nI want your midnights\nBut I'll be cleaning up bottles with you on New Year's Day\n\nPlease don't ever become a stranger\nWhose laugh I could recognize anywhere\nPlease don't ever become a stranger\nWhose laugh I could recognize anywhere"
};

document.addEventListener("DOMContentLoaded", () => {
    const songs = document.querySelectorAll(".song");
    const display = document.getElementById("lyrics-content");

    songs.forEach(song => {
        song.addEventListener("click", () => {
            songs.forEach(s => s.classList.remove("active"));
            song.classList.add("active");

            const songId = song.getAttribute("data-song");
            display.innerText = lyricsDatabase[songId] || "Lyrics not found.";
            
            // Auto resets layout container view back to top
            document.querySelector(".lyrics-screen").scrollTop = 0;
        });
    });
});