const lyricsDatabase = {
    "iforgotthatyouexisted": "How many days did I spend thinking\n'Bout how you did me wrong, wrong, wrong?\nLived in the shade you were throwing\n'Til my sunshine was gone, gone, gone\nAnd I couldn't get away from ya\nIn my feelings more than I had admitting to\nYour name on my lips, tongue-tied\nFree rent, living in my mind\n\nBut then something happened one magical night\nI forgot that you existed\nAnd I thought that it would kill me, but it didn't\nAnd it was so nice\nSo peaceful and quiet\nI forgot that you existed\nIt isn't love, it isn't hate, it's just indifference\nI forgot that you existed\n\nHow many days did I spend thinking\n'Bout how you did me wrong, wrong, wrong?\nLived in the shade you were throwing\n'Til my sunshine was gone, gone, gone\nAnd I couldn't get away from ya\nIn my feelings more than I had admitting to\nYour name on my lips, tongue-tied\nFree rent, living in my mind\n\nBut then something happened one magical night\nI forgot that you existed\nAnd I thought that it would kill me, but it didn't\nAnd it was so nice\nSo peaceful and quiet\nI forgot that you existed\nIt isn't love, it isn't hate, it's just indifference\nI forgot that you existed\n\nGot out some popcorn\nAs soon as my rep started shrinking\nI got out some popcorn\nAs soon as your name started sinking\nOh, my, my, my\nI forgot that you existed\nIt isn't love, it isn't hate, it's just indifference\nI forgot that you existed",

    "ithinkheknows": "I think he knows\nHis footprints on the sidewalk\nLead to where I can't stop go and there we are\nI think he knows\nHis hands around my cold hands\nWarm me up, it's a sweet plan, brand new spark\n\nLyrical smile, indigo eyes, hand on my thigh\nWe can follow the sparks, I'll drive\nLonesome business, taking reference\nHe's got that boyish look that I like in a man\nI think he knows\nI think he knows\n\nHe got my heartbeat skipping 20 beats at a time\nHe got that look, I think he knows I'm gonna make him mine\nI think he knows\nI think he knows\n\nHe got my heartbeat skipping 20 beats at a time\nHe got that look, I think he knows I'm gonna make him mine\nI think he knows\nI think he knows\n\nI think he knows\nHis footprints on the sidewalk\nLead to where I can't stop go and there we are\nI think he knows\nHis hands around my cold hands\nWarm me up, it's a sweet plan, brand new spark\n\nLyrical smile, indigo eyes, hand on my thigh\nWe can follow the sparks, I'll drive\nLonesome business, taking reference\nHe's got that boyish look that I like in a man\nI think he knows\nI think he knows\n\nHe got my heartbeat skipping 20 beats at a time\nHe got that look, I think he knows I'm gonna make him mine\nI think he knows\nI think he knows",

    "londonboy": "We can go driving in, on my scooter\nUh, you know, just round London\nSomething like that\n\nI love my hometown as much as Motown, I love SoCal\nAnd you know I love Springsteen, faded blue jeans, Tennessee whiskey\nBut something happened, I heard him laughing\nSaw the dimples first and then I knew the worst\nThat I'm a goner who's into stories\n\nYou know I love a London boy\nBoy, I fancy you\nAnd now I love a London boy\nI love in afternoon\n\nHe took me to Highgate, met his best mates\nNow I'm in a English pub, we're watching rugby\nHe loves my American smile, taking the long way home\nTo his flat, I love the way he talks\n\nYou know I love a London boy\nBoy, I fancy you\nAnd now I love a London boy\nI love in afternoon\n\nSo please show me Hackney\nDoesn't have to be anything fancy\nJust take me back to your place, babe\n\nYou know I love a London boy\nBoy, I fancy you\nAnd now I love a London boy\nI love in afternoon",

    "me": "I promise that you'll never find another like me\n\nI know that I'm a handful, baby, uh\nI know I never think before I jump\nAnd you're the kind of guy the ladies want\n(And there's a lot of cool chicks out there)\nI know that I went psycho on the phone\nI never leave well enough alone\nAnd trouble's gonna follow where I go\n(And there's a lot of cool chicks out there)\n\nBut one of these things is not like the others\nLike a rainbow with all of the colors\nBaby doll, when it comes to a lover\nI promise that you'll never find another like\n\nMe-e-e, ooh-ooh-ooh-ooh\nI'm the only one of me\nBaby, that's the fun of me\nEeh-eeh-eeh, ooh-ooh-ooh-ooh\nYou're the only one of you\nBaby, that's the fun of you\nAnd I promise that nobody's gonna love you like me\n\nI know I tend to make it about me\nI know you never get just what you see\nBut I will never bore you, baby\n(And there's a lot of lame guys out there)\nAnd when we had that fight out in the rain\nYou ran after me and called my name\nI never wanna see you walk away\n(And there's a lot of lame guys out there)\n\nBut one of these things is not like the others\nLike a rainbow with all of the colors\nBaby doll, when it comes to a lover\nI promise that you'll never find another like\n\nMe-e-e, ooh-ooh-ooh-ooh\nI'm the only one of me\nBaby, that's the fun of me\nEeh-eeh-eeh, ooh-ooh-ooh-ooh\nYou're the only one of you\nBaby, that's the fun of you\nAnd I promise that nobody's gonna love you like me\n\nHey, kids, spelling is fun!\nOur team is the best team\nI'm the one who loves you, baby\nOur team is the best team\nYou're the one who loves me, baby\n\nMe-e-e, ooh-ooh-ooh-ooh\nI'm the only one of me\nBaby, that's the fun of me\nEeh-eeh-eeh, ooh-ooh-ooh-ooh\nYou're the only one of you\nBaby, that's the fun of you\nAnd I promise that nobody's gonna love you like me",

    "cruelsummer": "Fever dream high in the quiet of the night\nYou know that I caught it\nBad, bad boy, shiny toy with a price\nYou know that I bought it\n\nKilling me slow, out the window\nI'm always waiting for you to be waiting below\nDevils roll the dice, angels roll their eyes\nWhat's it gonna be, for this visual design?\n\nAnd it's new, the shape of your body\nIt's blue, the feeling I've got\nAnd it's a cruel summer\nIt's cool, that's what I tell 'em\nNo rules in breakable heaven\nBut it's a cruel summer with you\n\nHang your head low in the glow of the vending machine\nI'm not dying\nYou say that we're fine, but you don't mean a thing\nAnd I'm not crying\n\nKilling me slow, out the window\nI'm always waiting for you to be waiting below\nDevils roll the dice, angels roll their eyes\nWhat's it gonna be, for this visual design?\n\nAnd it's new, the shape of your body\nIt's blue, the feeling I've got\nAnd it's a cruel summer\nIt's cool, that's what I tell 'em\nNo rules in breakable heaven\nBut it's a cruel summer with you\n\nI'm drunk in the back of the car\nAnd I cried like a baby coming home from the bar\nSaid, \"I'm fine,\" but it wasn't the truth\nI don't wanna keep secrets just to keep you\nAnd I snuck in through the garden gate\nEvery night that summer just to seal my fate\nAnd I scream, \"For whatever it's worth\nI love you, ain't that the worst thing you ever heard?\"\nHe looks up grinning like a devil\n\nAnd it's new, the shape of your body\nIt's blue, the feeling I've got\nAnd it's a cruel summer\nIt's cool, that's what I tell 'em\nNo rules in breakable heaven\nBut it's a cruel summer with you",

    "missamericana": "You know I adore you, I'm crazier for you\nThan I was at 16, lost in a filth scene\nRunning through rose thorns, structural patterns\nI'm high on the baseline\n\nNo cameras catch my tears when I'm crying\nMiss Americana and the Heartbreak Prince\nWe're data tracking, the flags are flying\nIt's been a long time coming, center lines align\nAnd I don't want to lose this fight\n\nMy town was a wasteland, full of the broken\nWe were too busy fighting the words unspoken\nNow I'm running down corridors looking for you\nHoping that you feel the same way too\n\nNo cameras catch my tears when I'm crying\nMiss Americana and the Heartbreak Prince\nWe're data tracking, the flags are flying\nIt's been a long time coming, center lines align\nAnd I don't want to lose this fight\n\nAnd they're cheering for the winning team\nBut we're just trying to survive the scene\nMiss Americana, the Heartbreak Prince\nWe're moving forward ever since",

    "soonyoullgetbetter": "The buttons of my coat were tangled in my hair\nIn the doctor's office lighting, I didn't tell you I was scared\nThat was the first time we were there\nHoly orange bottles, each night I pray to you\nDesperate people find faith, so now I pray to Jesus too\n\nAnd I know you're a fighter\nBut you'll get better soon\n'Cause you have to\n\nI paint the kitchen walls, I make the place look bright\nI pretend that everything is gonna be alright tonight\nBut I can't even sleep at night\n\nAnd I know you're a fighter\nBut you'll get better soon\n'Cause you have to\n\nOoh, you'll get better soon\nOoh, you'll get better soon\nOoh, you'll get better soon\n'Cause you have to",

    "itsnicetohaveafriend": "Ooh, ooh\n\nSchool bell rings, walk me home\nSidewalk chalk on the concrete zone\nLight pink skies up on the roof\nSunken eyes, checking for proof\n\nIt's nice to have a friend\nIt's nice to have a friend\n\nSleeping in tents, winter cold\nSharing secrets, getting old\nPass the note, write it down\nWe're the kings of this little town\n\nIt's nice to have a friend\nIt's nice to have a friend\n\nChurch bells ring, carry me home\nRice on the sidewalk, no longer alone\nLight pink skies up on the roof\nSunken eyes, we are the proof\n\nIt's nice to have a friend\nIt's nice to have a friend",

    "lover": "We could leave the Christmas lights up 'til January\nAnd this is our place, we make the rules\nAnd there's a dazzling haze, a mysterious way about you, dear\nHave I known you 20 seconds or 20 years?\n\nCan I go where you go?\nCan we always be this close forever and ever?\nAnd ah, take me out, and take me home\nYou're my, my, my, my...\nLover\n\nWe could let our friends crash in the living room\nThis is my place, I even make the rules\nAnd I'm highly suspicious that everyone who sees you wants you\nI've loved you three summers now, honey, but I want 'em all\n\nCan I go where you go?\nCan we always be this close forever and ever?\nAnd ah, take me out, and take me home\nYou're my, my, my, my...\nLover\n\nLadies and gentlemen, will you please stand?\nWith every guitar string scar on my hand\nI take this magnetic force of a man to be my home\nMy heart's been borrowed and yours has been blue\nAll's well that ends well to end up with you\nSwear to be overdramatic and true to my lover\n\nAnd you'll save all your dirtiest jokes for me\nAnd at every table, I'll save you a seat, lover\n\nCan I go where you go?\nCan we always be this close forever and ever?\nAnd ah, take me out, and take me home\nYou're my, my, my, my...\nOh, you're my, my, my, my...\nDarling, you're my, my, my, my...\nLover",

    "paperrings": "The moon is high like your friends were the night that we first met\nWent home and tried to stalk you on the internet\nNow I've read all of the books beside your bed\n\nI like shiny things, but I'd marry you with paper rings\nUh-huh, that's right\nDarling, you're the one I want, and I hate accidents\nExcept when we went from friends to this\n\nIn the winter, in the icy cold, we were moving fast\nTrying to make a good thing truly last\nNow I'm waking up right next to you\n\nI like shiny things, but I'd marry you with paper rings\nUh-huh, that's right\nDarling, you're the one I want, and I hate accidents\nExcept when we went from friends to this\n\nYou're the one I want, paper rings are enough\nYeah, paper rings are enough for our love",

    "falsegod": "We were crazy to think that this would work out fine\nRemember when I fell and broke my structural spine?\nYou were there to pick up all the pieces of me\nNow we're worshipping a false god in the dark, you see\n\nBut the altar is my hips\nAnd the ocean is your lips\nWe're still holding on\n\nThey all warned us about the dangers of the road\nBut we decided to carry this heavy load\nNo matter what they say, we're gonna survive\nKeeping this false god alive\n\nBut the altar is my hips\nAnd the ocean is your lips\nWe're still holding on\nYeah, we're holding on",

    "daylight": "My love was as cruel as the cities I walked through\nWrong choices made, and everything was out of view\nI've been sleeping in a dark room for twenty long years\nWith nothing but my inner fears\n\nBut I see daylight now, I see daylight\nAnd I only want to look at you\nI only want to see the light\n\nClearing the air, I breathed in the fresh morning sun\nRealizing that the battle has finally been won\nNo more running away from the ghosts of the past\nWe found a love that's built to last\n\nBut I see daylight now, I see daylight\nAnd I only want to look at you\nI only want to see the light\n\nI wanna be defined by the things that I love\nNot the things I hate, or the things I'm afraid of\nI think that you are what you love\nAnd I love daylight",

    "theman": "I'd be a fearless leader, I'd be an alpha type\nWhen everyone believes ya, what's that like?\n\nI'm so sick of running as fast as I can\nWearing out my shoes, wondering if I'd get there quicker\nIf I was a man\nAnd if I was a man, I'd be the man\n\nThey'd say I played the field before I found the one\nEverything I did would be considered fun\nInstead of being judged for the choices I make\nEvery single risk I take\n\nI'm so sick of running as fast as I can\nWearing out my shoes, wondering if I'd get there quicker\nIf I was a man\nAnd if I was a man, I'd be the man\n\nWhat's it like to boast about your money and power?\nEvery single minute, every single hour\nYeah, if I was a man, I'd be the man",

    "corneliastreet": "We were rent-sharing on Cornelia Street\nBack when the city felt so fresh and sweet\nI memorize the creaks in the floorboards clean\nBefore you ever knew what I could mean\n\nAnd I hope I never lose you, hope this never ends\nI'd never walk Cornelia Street again\nThat's the kind of heartbreak time won't ever mend\n\nWe were packing up our bags in the middle of July\nTrying not to look each other straight in the eye\nBut the memory of that place still lingers in my mind\nThe sweetest love I'll ever find\n\nAnd I hope I never lose you, hope this never ends\nI'd never walk Cornelia Street again\nThat's the kind of heartbreak time won't ever mend\n\nI transiently look back at the place we began\nCornelia Street, I'm doing the best I can",

    "youneedtocalmdown": "You are somebody that I don't know\nBut you're coming at my friends like a missile blow\nAnd I'm just like, \"Damn, it's 7:00 AM\"\n\nSay it in the street, that's a knock-out punch\nBut you say it in a tweet, that's a cop-out bunch\nAnd you need to calm down, you're being too loud\nAnd you need to just stop, data track lines drop\n\nYou need to calm down\nYou're being too loud\nJust step on my gown\nYou need to calm down\n\nAnd we see you over there on the internet\nComparing all the girls who are killing it\nBut we all know the truth of the crown\nSo you need to calm down",

    "thearcher": "Combat, I'm ready for the formal fight\nI strike first, then I stay awake all night\nI've been the archer, I've been the prey\nWho could ever leave me, darling?\nBut who could ever stay beside me anyway?\n\nDark side lines are creeping up on me now\nTrying to figure out the exact reason how\nI got myself into this mess once again\nLooking for a trusted friend\n\nI've been the archer, I've been the prey\nWho could ever leave me, darling?\nBut who could ever stay beside me anyway?\n\nThey see right through me, they see right through\nI see right through me, I see right through you\n'Cause all of my enemies started out friends\nHelp me hold onto you",

    "deathbyathousandcuts": "Saying goodbye is death by a thousand cuts\nI ask the traffic lights if it'll be alright\nThey say, \"I don't know\"\nI look across the room, your shadow's in the door\nBut now I'm just pacing on the hardwood floor\n\nOur songs, our films, our united history\nNow it's all turned into a complete mystery\nI draw the blinds and try to block out the light\nBut I still see you in the middle of the night\n\nSaying goodbye is death by a thousand cuts\nI ask the traffic lights if it'll be alright\nThey say, \"I don't know\"\nI look across the room, your shadow's in the door\nBut now I'm just pacing on the hardwood floor\n\nTry to fix it, try to make it right\nBut we're just spinning in the dark tonight\nDeath by a thousand cuts",

    "afterglow": "I blew things out of proportion, now you're blue\nI went and blamed it all on you\nI didn't mean to hurt you, baby, it's my crime\n\nMeet me in the afterglow\nOh, meet me in the afterglow\nWhere everything is quiet and the light lines flow\n\nI'm pinning all my demons down to the floor\nI don't wanna fight with you anymore\nLet's just clear the air and make things right\nUnderneath the stars tonight\n\nMeet me in the afterglow\nOh, meet me in the afterglow\nWhere everything is quiet and the light lines flow\n\nSorry that I hurt you, meet me in the afterglow"
};

document.addEventListener("DOMContentLoaded", () => {
    const songs = document.querySelectorAll(".song");
    const display = document.getElementById("lyrics-content");

    songs.forEach(song => {
        song.addEventListener("click", () => {
            songs.forEach(s => s.classList.remove("active"));
            song.classList.add("active");

            const songId = song.getAttribute("data-song");
            display.innerText = lyricsDatabase[songId] || "Lyrics not found.";
            
            // Auto resets layout view container smoothly back to top
            document.querySelector(".lyrics-screen").scrollTop = 0;
        });
    });
});